config/routes.rb
Rails.application.routes.draw do
  resources :namespaces
  resources :domains do
    get :image
    get :video
    get :audio
    get :search
    get :users
    get :download_file
  end
  root 'welcome#index'
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/domain.rb
class Domain < ApplicationRecord
  extend Enumerize
  validates :name, :protocol, :host, presence: true
  before_validation :check_api, on: :create
  serialize :namespace, Array

  enumerize :protocol, in: %w[http https]

  def check_api
    Namespace.all.each do |name|
      url = "#{protocol}://#{host}#{name.namespace}"
      response = HTTParty.get(url)
      namespace << name.namespace if response.code == 200
    end
  end
end

app/models/namespace.rb
class Namespace < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  add_breadcrumb "<a class='breadcrumb' href='/' style='margin-left: 20px;'>Home</a>".html_safe
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  add_breadcrumb "<a class='breadcrumb' href='/domains'>Domain</a>".html_safe
  before_action :set_domain, only: [:show, :edit, :update, :destroy, :image, :video, :audio, :users, :search]
  before_action :set_breadcrumb, only: [:edit, :image, :video, :audio, :users, :search]

  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all.reverse
    @pagy, @records = pagy_array(@domains, count: @domains.count )
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
    add_breadcrumb "<a class='breadcrumb'>#{@domain.name}</a>".html_safe
  end

  # GET /domains/new
  def new
    add_breadcrumb "<a class='breadcrumb'>New</a>".html_safe
    @domain = Domain.new
  end

  # GET /domains/new
  def image
    add_breadcrumb "<a class='breadcrumb' >Image</a>".html_safe
    response = Connect.new(@domain).mount_url('image', 20, params[:page] || 1)
    if response.code.to_i == 200
      @gallery = JSON.parse(response.read_body, symbolize_names: true)
      @pagy, @records = pagy_array(@gallery, count: response.header[:'x-wp-total'])
    else
      redirect_to request.referer, notice: 'No image found.'
    end
  end

  def video
    add_breadcrumb "<a class='breadcrumb' >Video</a>".html_safe
    response = Connect.new(@domain).mount_url('video', 20, params[:page] || 1) 
    if response.code.to_i == 200
      @gallery = JSON.parse(response.read_body, symbolize_names: true)
      @pagy, @records = pagy_array(@gallery, count: response.header[:'x-wp-total'])
    else
      redirect_to request.referer, notice: 'No video found.'
    end
  end

  def audio
    add_breadcrumb "<a class='breadcrumb' >Audio</a>".html_safe
    response = Connect.new(@domain).mount_url('audio', 20, params[:page] || 1)
    if response.code.to_i == 200
      @gallery = JSON.parse(response.read_body, symbolize_names: true)
      @pagy, @records = pagy_array(@gallery, count: response.header[:'x-wp-total'])
    else
      redirect_to request.referer, notice: 'No audio found.'
    end
  end

  def users
    add_breadcrumb "<a class='breadcrumb' >Users</a>".html_safe
    response = Connect.new(@domain).users(20, params[:page] || 1)
    if response.code.to_i == 200
      @gallery = JSON.parse(response.read_body, symbolize_names: true)
      @pagy, @records = pagy_array(@gallery, count: response.header[:'x-wp-total'])
    else
      redirect_to request.referer, notice: 'No users found.'
    end
  end

  def search
    add_breadcrumb "<a class='breadcrumb' >Search</a>".html_safe
    response = Connect.new(@domain).search(params[:q], 20, params[:page] || 1)
    if response.code.to_i == 200
      @gallery = JSON.parse(response.read_body, symbolize_names: true)
      @pagy, @records = pagy_array(@gallery, count: response.header[:'x-wp-total'])
    else
      redirect_to request.referer, notice: 'No file found.'
    end
  end

  def download_file
    url = params[:url]
    response = HTTParty.get(url)
    if response.code.to_i == 200
      tempfile = Down.download(url) 
      data = open(tempfile.path).read
      send_data data, disposition: 'attachment', filename: tempfile.original_filename
    else
      redirect_to request.referer, notice: 'No download found.'
    end
  end


  # GET /domains/1/edit
  def edit
    add_breadcrumb "<a class='breadcrumb' >Edit</a>".html_safe
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)
    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.'}
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id] || params[:domain_id])
    end

    def set_breadcrumb
      add_breadcrumb "<a class='breadcrumb' href='#{domain_path(@domain)}'>#{@domain.name}</a>".html_safe
    end

    # Only allow a list of trusted parameters through.
    def domain_params
      params.require(:domain).permit(:name, :protocol, :host)
    end
end

app/controllers/namespaces_controller.rb
class NamespacesController < ApplicationController
  before_action :set_namespace, only: [:show, :edit, :update, :destroy]

  # GET /namespaces
  # GET /namespaces.json
  def index
    @namespaces = Namespace.all
  end

  # GET /namespaces/1
  # GET /namespaces/1.json
  def show
  end

  # GET /namespaces/new
  def new
    @namespace = Namespace.new
  end

  # GET /namespaces/1/edit
  def edit
  end

  # POST /namespaces
  # POST /namespaces.json
  def create
    @namespace = Namespace.new(namespace_params)

    respond_to do |format|
      if @namespace.save
        format.html { redirect_to @namespace, notice: 'Namespace was successfully created.' }
        format.json { render :show, status: :created, location: @namespace }
      else
        format.html { render :new }
        format.json { render json: @namespace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /namespaces/1
  # PATCH/PUT /namespaces/1.json
  def update
    respond_to do |format|
      if @namespace.update(namespace_params)
        format.html { redirect_to @namespace, notice: 'Namespace was successfully updated.' }
        format.json { render :show, status: :ok, location: @namespace }
      else
        format.html { render :edit }
        format.json { render json: @namespace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /namespaces/1
  # DELETE /namespaces/1.json
  def destroy
    @namespace.destroy
    respond_to do |format|
      format.html { redirect_to namespaces_url, notice: 'Namespace was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_namespace
      @namespace = Namespace.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def namespace_params
      params.require(:namespace).permit(:namespace)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/namespaces_helper.rb
module NamespacesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/domains/_form.html.erb
      <div class="row">
        <%= form_with(model: domain, local: true, class:"col s12") do |form| %>
          <% if domain.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

              <ul>
                <% domain.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row">
            <div class="input-field col s3">
              <%= form.label :name %>
              <%= form.text_field :name, class:"validate" %>
            </div>
            <div class="input-field col s3">
            <%= form.select :protocol, Domain.protocol.values %>
            </div>
            <div class="input-field col s3">
              <%= form.label :host %>
              <%= form.text_field :host, class:"validate" %>
            </div>
            <div class="input-field col s3">
              <%= form.submit class:"waves-effect waves-light btn" %>
              <%= link_to 'Back', domains_path, class:"waves-effect waves-light btn" %>
            </div>
          </div>
        <% end %>
      </div>

app/views/domains/audio.html.erb
<div class="row">
  <div class="col s12">
    <div style="padding: 35px;" align="center" class="card">
      <div class="row">
        <div class="card-title">
          <b>Audio</b>
        </div>
      </div>
      <div class="row">
        <p id="notice"><%= notice %></p>
        <div class="col s12">
          <table class="highlight responsive-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>URL</th>
                <th>Player</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <% @gallery.each do |file| %>
                <tr>
                  <td><%= file[:id] %></td>
                  <td><%= file[:source_url] %></td>
                  <td>
                    <audio controls played preload>
                      <source src="<%= file[:source_url] %>" >
                    </audio>
                  </td>
                  <td><%= link_to "Download", domain_download_file_path(@domain, url: file[:source_url]) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="col s6 ">
          <div class="pagy-materialize-nav pagination left" style="padding: 10px;">
            <ul class="pagination">
              Showing <%= @pagy.from %> to <%= @pagy.to %> of <%= @pagy.count %> entries
            </ul>
          </div>
        </div>
        <div class="col s6"  align="right">
            <%== pagy_materialize_nav(@pagy) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/domains/edit.html.erb
<div class="row">
  <div class="col s12">
    <div style="padding: 35px;" align="center" class="card">
      <div class="row">
        <div class="left card-title">
          <b>Editing Domain</b>
        </div>
      </div>
      <%= render 'form', domain: @domain %>
    </div>
  </div>
</div>

app/views/domains/image.html.erb
<div class="row">
  <div class="col s12">
    <div style="padding: 10px;"  class="card">
      <div class="row">
        <div class="left card-title">
          <p id="notice"><%= notice %></p>
        </div>
      </div>
      <div class="row">
        <% @gallery.each do |file| %> 
          <div class="col s12 m3">
            <div class="card">
              <div class="card-image img-resize">
                <img class="materialboxed responsive-img" src="<%= file[:source_url] %>">
              </div>
              <div class="card-content">
                <p><b>Name:</b> <%= file[:title][:rendered] %></p>
              </div>
              <div class="card-action center">
                <%= link_to "Download", domain_download_file_path(@domain, url: file[:source_url]), class:"waves-effect waves-light btn" %>
              </div>
            </div>
          </div>
        <% end %> 
      </div>
      
      <div class="row">
        <div class="col s6">
          <div class="pagy-materialize-nav pagination left" style="padding: 10px;">
            <ul class="pagination">
              Showing <%= @pagy.from %> to <%= @pagy.to %> of <%= @pagy.count %> entries
            </ul>
          </div>
        </div>
        <div class="col s6"  align="right">
          <%== pagy_materialize_nav(@pagy) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/domains/index.html.erb
<div class="row">
  <div class="col s12">
    <div style="padding: 35px;" align="center" class="card">
      <div class="row">
        <%= link_to "New Domain", new_domain_path , class:"waves-effect waves-light btn left" %>
        <div class="card-title">
          <b>Domains</b>
          <p id="notice"><%= notice %></p>
        </div>
      </div>
      <div class="row">
        <div class="col s12">
          <table class="highlight responsive-table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Protocol</th>
                <th>Host</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @records.each do |domain| %>
                <tr>
                  <td><%= domain.name %></td>
                  <td><%= domain.protocol %></td>
                  <td><%= domain.host %></td>
                  <td><%= link_to 'Show', domain %></td>
                  <td><%= link_to 'Edit', edit_domain_path(domain) %></td>
                  <td><%= link_to 'Destroy', domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="col s12 center">
          <%== pagy_materialize_nav(@pagy) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/domains/new.html.erb
<div class="row">
  <div class="col s12">
    <div style="padding: 35px;" align="center" class="card">
      <div class="row">
        <div class="left card-title">
          <b>New Domain</b>
        </div>
      </div>
      <%= render 'form', domain: @domain %>
    </div>
  </div>
</div>

app/views/domains/search.html.erb
<div class="row">
  <div class="col s12">
    <div style="padding: 35px;" align="center" class="card">
      <div class="row">
        <div class="card-title">
          <b>File</b>
        </div>
      </div>
      <div class="row">
        <p id="notice"><%= notice %></p>
        <div class="col s12">
          <table class="highlight responsive-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>URL</th>
                <th colspan="2">Action</th>
              </tr>
            </thead>
            <tbody>
              <% @gallery.each do |file| %>
                <tr>
                  <td><%= file[:id] %></td>
                  <td><%= file[:source_url] %></td>
                  <td><%= link_to "Open", file[:source_url], target: '_blank' %></td>
                  <td><%= link_to "Download", domain_download_file_path(@domain, url: file[:source_url]) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="col s6 ">
          <div class="pagy-materialize-nav pagination left" style="padding: 10px;">
            <ul class="pagination">
              Showing <%= @pagy.from %> to <%= @pagy.to %> of <%= @pagy.count %> entries
            </ul>
          </div>
        </div>
        <div class="col s6"  align="right">
            <%== pagy_materialize_nav(@pagy) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/domains/show.html.erb
<div class="row">
  <div class="col s12">
    <div style="padding: 10px;" class="card">
      <div class="row">
        <div class="left card-title">
        </div>
      </div>
      <div class="row">
        <div class="col s12 m6 offset-m3">
          <div class="col s12">
            <div class="card horizontal">
              <div class="card-stacked">
                <div class="card-content">
                  <div class="row">
                    <%= form_tag(domain_search_path(@domain), method: :get) do %>
                      <div class="input-field col s10 m10">
                        <%= label_tag :q, 'Search for extension' %>
                        <%= text_field_tag :q  %>
                      </div>
                      <div class="input-field col s2 m2">
                        <button class="waves-effect waves-light btn-floating left" type='submite' ><i class="material-icons left">search</i></button>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <div style="padding: 5px;" align="center" class="card">
      <div class="row">
        <div class="center card-title">
          <p id="notice"><%= notice %></p>
        </div>
      </div>
      <div class="row">
        <div class="col s6 m3">
          <%= link_to domain_image_path(@domain) do %>
            <div style="padding: 30px;" class="card horizontal grey lighten-3 col s12 waves-effect">
              <i class="indigo-text text-lighten-1 large material-icons">view_list</i>
              <span class="indigo-text text-lighten-1"><h5>Endpoints</h5></span>
            </div>
          <% end %>
        </div>

        <div class="col s6 m3">
          <%= link_to domain_users_path(@domain) do %>
            <div style="padding: 30px;" class="card horizontal grey lighten-3 col s12 waves-effect">
              <i class="indigo-text text-lighten-1 large material-icons">supervisor_account</i>
              <span class="indigo-text text-lighten-1"><h5>Users</h5></span>
            </div>
          <% end %>
        </div>

        <div class="col s6 m3">
          <%= link_to domain_search_path(@domain, q: '') do %>
            <div style="padding: 30px;" class="card horizontal grey lighten-3 col s12 waves-effect">
              <i class="indigo-text text-lighten-1 large material-icons">folder</i>
              <span class="indigo-text text-lighten-1"><h5>All Files</h5></span>
            </div>
          <% end %>
        </div>

        <div class="col s6 m3">
          <%= link_to domain_image_path(@domain) do %>
            <div style="padding: 30px;" class="card horizontal grey lighten-3 col s12 waves-effect">
              <i class="indigo-text text-lighten-1 large material-icons">image</i>
              <span class="indigo-text text-lighten-1"><h5>Image</h5></span>
            </div>
          <% end %>
        </div>

        <div class="col s6 m3">
          <%= link_to domain_video_path(@domain) do %>
            <div style="padding: 30px;" class="card horizontal grey lighten-3 col s12 waves-effect">
              <i class="indigo-text text-lighten-1 large material-icons">video_library</i>
              <span class="indigo-text text-lighten-1"><h5>Video</h5></span>
            </div>
          <% end %>
        </div>

        <div class="col s6 m3">
          <%= link_to domain_audio_path(@domain) do %>
            <div style="padding: 30px;" class="card horizontal grey lighten-3 col s12 waves-effect">
              <i class="indigo-text text-lighten-1 large material-icons">library_music</i>
              <span class="indigo-text text-lighten-1"><h5>Audio</h5></span>
            </div>
          <% end %>
        </div>

        <div class="col s6 m3">
          <%= link_to domain_search_path(@domain, q: '.txt') do %>
            <div style="padding: 30px;" class="card horizontal grey lighten-3 col s12 waves-effect">
              <i class="indigo-text text-lighten-1 large material-icons">insert_drive_file</i>
              <span class="indigo-text text-lighten-1"><h5>TXT</h5></span>
            </div>
          <% end %>
        </div>

        <div class="col s6 m3">
          <%= link_to domain_search_path(@domain, q: '.pdf') do %>
            <div style="padding: 30px;" class="card horizontal grey lighten-3 col s12 waves-effect">
              <i class="indigo-text text-lighten-1 large material-icons">insert_drive_file</i>
              <span class="indigo-text text-lighten-1"><h5>PDF</h5></span>
            </div>
          <% end %>
        </div>

        <div class="col s6 m3">
          <%= link_to domain_search_path(@domain, q: '.doc') do %>
            <div style="padding: 30px;" class="card horizontal grey lighten-3 col s12 waves-effect">
              <i class="indigo-text text-lighten-1 large material-icons">insert_drive_file</i>
              <span class="indigo-text text-lighten-1"><h5>DOC</h5></span>
            </div>
          <% end %>
        </div>

        <div class="col s6 m3">
          <%= link_to domain_search_path(@domain, q: '.xls') do %>
            <div style="padding: 30px;" class="card horizontal grey lighten-3 col s12 waves-effect">
              <i class="indigo-text text-lighten-1 large material-icons">insert_drive_file</i>
              <span class="indigo-text text-lighten-1"><h5>XLS</h5></span>
            </div>
          <% end %>
        </div>

        <div class="col s6 m3">
          <%= link_to domain_search_path(@domain, q: '.ppt') do %>
            <div style="padding: 30px;" class="card horizontal grey lighten-3 col s12 waves-effect">
              <i class="indigo-text text-lighten-1 large material-icons">insert_drive_file</i>
              <span class="indigo-text text-lighten-1"><h5>PPT</h5></span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/domains/video.html.erb
<div class="row">
  <div class="col s12">
    <div style="padding: 10px;"  class="card">
      <div class="row">
        <div class="center card-title">
            <p id="notice"><%= notice %></p>
        </div>
      </div>
      <div class="row">
        <% @gallery.each do |file| %> 
          <div class="col s12 m3">
            <div class="card">
              <div class="card-image center">
                <video   width="100%" height="300" controls>
                    <source src="<%= file[:source_url] %>">
                </video>
              </div>
              <div class="card-action center">
                <%= link_to "Open", file[:source_url], target: '_blank', class:"waves-effect waves-light btn" %>
              </div>
            </div>
          </div>
        <% end %> 
      </div>
      <div class="row">
        <div class="col s6">
          <div class="pagy-materialize-nav pagination left" style="padding: 10px;">
            <ul class="pagination">
              Showing <%= @pagy.from %> to <%= @pagy.to %> of <%= @pagy.count %> entries
            </ul>
          </div>
        </div>
        <div class="col s6"  align="right">
          <%== pagy_materialize_nav(@pagy) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Wp Consume</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css'>
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/font/material-design-icons/Material-Design-Icons.woff'>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body data-turbolinks="false">
  <ul id="slide-out" class="side-nav fixed z-depth-2">
    <li class="center no-padding">
      <div class="indigo darken-2 white-text" style="height: 180px;">
        <div class="row">
          <img style="margin-top: 5%;" width="100" height="100" src="https://raw.githubusercontent.com/uiltonlopes/uiltonlopes.github.io/master/images/logo.png" class="circle responsive-img" />

          <p style="margin-top: -13%;">
            WP Consume
          </p>
        </div>
      </div>
    </li>

    <li><b><%= link_to  "Domain", domains_path %></b></li>
    <li><b><%= link_to  "Namespace", namespaces_path %></b></li>

    <ul class="collapsible" data-collapsible="accordion">
      <li id="dash_users">
        <div id="dash_users_header" class="collapsible-header waves-effect"><b>Documentation</b></div>
        <div id="dash_users_body" class="collapsible-body">
          <ul>
            <li id="users_seller">
              <a class="waves-effect" style="text-decoration: none;" href="#!">Seller</a>
            </li>

            <li id="users_customer">
              <a class="waves-effect" style="text-decoration: none;" href="#!">Customer</a>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </ul>

  <header>
    <ul class="dropdown-content" id="user_dropdown">
      <li><a class="indigo-text" href="#!">Profile</a></li>
      <li><a class="indigo-text" href="#!">Logout</a></li>
    </ul>

    <nav class="indigo" role="navigation">
      <div class="nav-wrapper">
        <a data-activates="slide-out" class="button-collapse show-on-" href="#!"><img style="margin-top: 17px; margin-left: 5px;" src="https://raw.githubusercontent.com/uiltonlopes/uiltonlopes.github.io/master/images/logo.png" /></a>

        <ul class="right hide-on-med-and-down">
          <li>
            <a class='right dropdown-button' href='' data-activates='user_dropdown'><i class=' material-icons'>account_circle</i></a>
          </li>
        </ul>

        <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
      </div>
    </nav>

    <nav>
      <div class="nav-wrapper indigo darken-2">
      <%= render_breadcrumbs :separator => "" %>
      <div style="margin-right: 20px;" id="timestamp" class="right"></div>
      </div>
    </nav>
  </header>

  <main>
    <%= yield %>
  </main>

  <footer class="indigo page-footer">
    <div class="container">
      <div class="row">
        <div class="col s12">
          <h5 class="white-text">Credits</h5>
          <ul id='credits'>
            <li>
              Icons made by <a href="https://material.io/icons/">Google</a>, available under <a href="https://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache License Version 2.0</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
         <span>Made By <a style='font-weight: bold;' href="https://github.com/uiltonlopes" target="_blank">Uilton Lopes</a></span>
      </div>
    </div>
  </footer>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js'></script>
  <script>
    $(function () {

      $('.button-collapse').sideNav();

      $('.collapsible').collapsible();

      $('select').material_select();
    });
  </script>
  </body>
</html>

app/views/namespaces/_form.html.erb
<%= form_with(model: namespace, local: true) do |form| %>
  <% if namespace.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(namespace.errors.count, "error") %> prohibited this namespace from being saved:</h2>

      <ul>
        <% namespace.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :namespace %>
    <%= form.text_field :namespace %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/namespaces/edit.html.erb
<h1>Editing Namespace</h1>

<%= render 'form', namespace: @namespace %>

<%= link_to 'Show', @namespace %> |
<%= link_to 'Back', namespaces_path %>

app/views/namespaces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Namespaces</h1>

<table>
  <thead>
    <tr>
      <th>Namespace</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @namespaces.each do |namespace| %>
      <tr>
        <td><%= namespace.namespace %></td>
        <td><%= link_to 'Show', namespace %></td>
        <td><%= link_to 'Edit', edit_namespace_path(namespace) %></td>
        <td><%= link_to 'Destroy', namespace, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Namespace', new_namespace_path %>

app/views/namespaces/new.html.erb
<h1>New Namespace</h1>

<%= render 'form', namespace: @namespace %>

<%= link_to 'Back', namespaces_path %>

app/views/namespaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Namespace:</strong>
  <%= @namespace.namespace %>
</p>

<%= link_to 'Edit', edit_namespace_path(@namespace) %> |
<%= link_to 'Back', namespaces_path %>